spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: collabed
      port: 27017
      host: localhost
      auto-index-creation: true
      uuid-representation: standard
springdoc:
  api-docs:
    path: /api-docs
client:
  host: http://localhost:5173
